alias tfp='terraform plan'
# Add tfplan to gitignore
alias tfpo='terraform plan -out tfplan'

alias tfa='terraform apply'
alias tfaa='terraform apply -auto-approve'
alias tfap='terraform apply tfplan'

alias tfv='terraform validate'
alias tfi='terraform init'
alias tfg='terraform graph'
alias tffu='terraform force-unlock'
alias tfc='terraform console'
alias tfd='terraform destroy'
alias tfs='terraform show'
alias tft='terrafrom taint'
alias tfut='terraform untaint'
alias tfs='terraform state'
alias tfw='terraform workspace'
alias tfgu='terraform get --update'
